services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: development
    restart: always
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mern-react-express
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      target: development
    restart: always
    ports:
      - 666:666
    #expose:
    #  - 666
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mern-express-mongo
      - mern-react-express
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:4.2.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: portfolio
    volumes:
      - ./data:/data/db
      #- /data/configdb
    networks:
      - mern-express-mongo
    expose:
      - 27017

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017
    networks:
      - mern-express-mongo
    depends_on:
      - mongo

networks:
  mern-react-express:
  mern-express-mongo:
